project:
  type: book
  output-dir: docs

book:
  title: "Yudum Paçin"
  repo-url: "https://github.com/pjournal/mef06-yudumpacin"
  chapters:
    - index.qmd
    - assignment1.Rmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

